"use client";
import { FormEvent,useCallback,useEffect,useMemo,useRef,useState } from "react";
import { supabaseBrowser } from "@/app/lib/supabaseBrowser";
import { mergeAcceptedSuggestions } from "@/app/lib/textbookMappingSuggestions.mjs";
import { createSynchronousMutationLock, createTextbookAdminRequestGuard } from "@/app/lib/textbookAdminRequestGuard.mjs";

type Source={id:string;book_name:string;edition:string;board:string;class_number:number;subject:string;status:string;version:number;sha256?:string;processing_revision:number;page_count?:number;processing_error?:string};
type Page={page_number:number;extracted_text:string;reviewed_text?:string;review_status:string};
type Subject={id:number;board:string;class_number:number;subject_name:string;chapters:{id:number;chapter_name:string;topics:{id:number;topic_name:string;is_active:boolean}[]}[]};
type Mapping={subjectId:string;chapterId:string;topicId:string;pageFrom:string;pageTo:string};
type SourceIdentity={sourceId:string;version:number;sha256:string;processingRevision:number};
type Suggestion={subjectId:number;subjectName:string;chapterId:number;chapterName:string;topicId:number;topicName:string;pageFrom:number;pageTo:number;matchingHeading:string;evidence:{pageNumber:number;text:string}[];reason:string;selected:boolean};
type Unresolved={chapterId:number;chapterName:string;topicId:number;topicName:string;reason:string};
type DraftWork={draftMappings:Mapping[];suggestions:Suggestion[];unresolved:Unresolved[];suggestionSource:SourceIdentity|null;acceptedSuggestionSource:SourceIdentity|null;map:{subjectId:string;chapterId:string;topicId:string;pageFrom:string;pageTo:string}};
const sourceWorkKey=(source:Source)=>`${source.id}:v${source.version}:r${source.processing_revision}:${source.sha256||"unprocessed"}`;

export default function TextbooksPage(){
 const [password,setPassword]=useState(""); const [sources,setSources]=useState<Source[]>([]); const [selected,setSelected]=useState<Source|null>(null);
 const [pages,setPages]=useState<Page[]>([]); const [catalog,setCatalog]=useState<Subject[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 const [map,setMap]=useState({subjectId:"",chapterId:"",topicId:"",pageFrom:"1",pageTo:"1"});
 const [draftMappings,setDraftMappings]=useState<Mapping[]>([]);
 const [suggestions,setSuggestions]=useState<Suggestion[]>([]); const [unresolved,setUnresolved]=useState<Unresolved[]>([]);
 const [suggestionSource,setSuggestionSource]=useState<SourceIdentity|null>(null); const [acceptedSuggestionSource,setAcceptedSuggestionSource]=useState<SourceIdentity|null>(null);
 const workBySource=useRef<Record<string,DraftWork>>({});
 const requestGuard=useRef(createTextbookAdminRequestGuard());
 const mutationLock=useRef(createSynchronousMutationLock());
 const headers=useMemo(()=>({"x-admin-password":password}),[password]);
 const load=useCallback(async()=>{if(!password)return;const [a,b]=await Promise.all([fetch("/api/admin/textbooks",{headers}),fetch("/api/admin/textbooks?catalog=1",{headers})]);const x=await a.json(),y=await b.json();if(x.ok)setSources(x.sources);if(y.ok)setCatalog(y.subjects||[]);},[headers,password]);
 useEffect(()=>{void load()},[load]);
 async function detail(id:string,{preserveCurrent=true}:{preserveCurrent?:boolean}={}){const ticket=requestGuard.current.beginDetail(id);if(preserveCurrent&&selected)workBySource.current[sourceWorkKey(selected)]={draftMappings,suggestions,unresolved,suggestionSource,acceptedSuggestionSource,map};const r=await fetch(`/api/admin/textbooks?id=${id}`,{headers}),d=await r.json();if(!d.ok){if(requestGuard.current.acceptDetail(ticket,id))setMessage(d.error);return}if(!requestGuard.current.acceptDetail(ticket,d.source?.id))return;const next:Source=d.source,key=sourceWorkKey(next),saved=workBySource.current[key],otherIdentity=Object.keys(workBySource.current).some(k=>k.startsWith(`${next.id}:`)&&k!==key);requestGuard.current.select(key);setSelected(next);setPages(d.pages||[]);if(saved){setDraftMappings(saved.draftMappings);setSuggestions(saved.suggestions);setUnresolved(saved.unresolved);setSuggestionSource(saved.suggestionSource);setAcceptedSuggestionSource(saved.acceptedSuggestionSource);setMap(saved.map)}else{setDraftMappings((d.mappings||[]).map((m:any)=>({subjectId:String(m.subject_id),chapterId:String(m.chapter_id),topicId:String(m.topic_id),pageFrom:String(m.page_from),pageTo:String(m.page_to)})));setSuggestions([]);setUnresolved([]);setSuggestionSource(null);setAcceptedSuggestionSource(null);setMap({subjectId:"",chapterId:"",topicId:"",pageFrom:"1",pageTo:String(next.page_count||1)});if(otherIdentity)setMessage("This source has a new processed identity. Earlier unsaved work was retained separately and was not reused.")}}
 async function upload(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setMessage("");
  try{
   const data=new FormData(e.currentTarget),file=data.get("pdf");if(!(file instanceof File))throw new Error("Choose a PDF.");
   const payload={board:data.get("board"),classNumber:data.get("classNumber"),subject:data.get("subject"),bookName:data.get("bookName"),edition:data.get("edition"),fileName:file.name,fileSize:file.size,fileType:file.type};
   const r=await fetch("/api/admin/textbooks",{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Could not prepare upload.");
   const uploaded=await supabaseBrowser.storage.from("textbook-pdfs").uploadToSignedUrl(d.upload.path,d.upload.token,file,{contentType:"application/pdf",upsert:false});
   if(uploaded.error)throw uploaded.error;
   const finalized=await fetch("/api/admin/textbooks",{method:"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({sourceId:d.source.id,action:"finalize_upload"})}),done=await finalized.json();
   if(!finalized.ok||!done.ok)throw new Error(done.error||"Upload could not be finalized.");
   setMessage("Draft uploaded directly to private storage. Run processing next.");await load();await detail(d.source.id);
  }catch(error:any){setMessage(error?.message||"Upload failed.")}finally{setBusy(false)}
 }
 async function action(action:string,extra:any={}){if(!selected)return;const lockOwner=mutationLock.current.acquire();if(!lockOwner)return;const origin=selected,ticket=requestGuard.current.begin("mutation");setBusy(true);try{const url=action==="process"?"/api/admin/textbooks/process":"/api/admin/textbooks",body=action==="process"?{sourceId:origin.id}:{sourceId:origin.id,action,...extra};const r=await fetch(url,{method:action==="process"?"POST":"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!requestGuard.current.accept(ticket))return;setMessage(d.ok?`${action.replace("_"," ")} complete.`:d.error);if(d.ok&&action==="review")setPages(current=>current.map(page=>page.page_number===extra.pageNumber?{...page,reviewed_text:extra.reviewedText,review_status:extra.reviewStatus}:page));else if(d.ok){if(action==="save_mappings")delete workBySource.current[sourceWorkKey(origin)];await load();if(requestGuard.current.accept(ticket))await detail(origin.id,{preserveCurrent:action!=="save_mappings"})}}catch(error:any){if(requestGuard.current.accept(ticket))setMessage(error?.message||"Textbook action failed.")}finally{const released=mutationLock.current.release(lockOwner);if(released&&requestGuard.current.isLatest(ticket))setBusy(false)}}
 async function generateSuggestions(){if(!selected)return;const origin=selected,ticket=requestGuard.current.begin("suggestion");setBusy(true);try{const expectedSource={sourceId:origin.id,version:origin.version,sha256:origin.sha256,processingRevision:origin.processing_revision};const r=await fetch("/api/admin/textbooks",{method:"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({sourceId:origin.id,action:"suggest_mappings",expectedSource})}),d=await r.json();if(!requestGuard.current.accept(ticket))return;if(!r.ok||!d.ok)throw new Error(d.error||"Could not generate suggestions.");setSuggestionSource(d.sourceIdentity);setSuggestions(current=>{const edited=new Map(current.map(item=>[String(item.topicId),item]));return (d.suggestions||[]).map((item:Suggestion)=>edited.get(String(item.topicId))||{...item,selected:true})});setUnresolved(d.unresolved||[]);setMessage(`Generated ${d.suggestions?.length||0} conservative mapping suggestions. Existing draft mappings were not changed.`);}catch(error:any){if(requestGuard.current.accept(ticket))setMessage(error?.message||"Could not generate suggestions.")}finally{if(requestGuard.current.isLatest(ticket))setBusy(false)}}
 function acceptSuggestions(){if(!suggestionSource)return;const acceptedCount=suggestions.filter(item=>item.selected).length;setDraftMappings(current=>mergeAcceptedSuggestions(current,suggestions));setAcceptedSuggestionSource(suggestionSource);setMessage(`${acceptedCount} selected suggestions copied into the unsaved draft. Review them, then save all draft mappings explicitly.`);}
 async function openPdf(){if(!selected)return;const r=await fetch(`/api/admin/textbooks/pdf?id=${selected.id}`,{headers}),d=await r.json();if(d.ok)window.open(d.url,"_blank","noopener,noreferrer");else setMessage(d.error);}
 const subject=catalog.find(s=>String(s.id)===map.subjectId),chapter=subject?.chapters.find(c=>String(c.id)===map.chapterId);
 return <section className="space-y-5"><div><h1 className="text-2xl font-semibold">Textbook Teaching</h1><p className="text-sm text-slate-500">Private PDF ingestion, page review, curriculum mapping and publication.</p></div>
  {message&&<div className="rounded border bg-white p-3 text-sm">{message}</div>}
  <input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" className="w-full rounded border p-2"/>
  <form onSubmit={upload} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3">
   <input name="board" defaultValue="CBSE" required className="rounded border p-2"/><input name="classNumber" type="number" min="1" max="12" defaultValue="7" required className="rounded border p-2"/><input name="subject" defaultValue="English" required className="rounded border p-2"/>
   <input name="bookName" defaultValue="Poorvi" required placeholder="Book" className="rounded border p-2"/><input name="edition" required placeholder="Edition / year" className="rounded border p-2"/><input name="pdf" type="file" accept="application/pdf,.pdf" required className="rounded border p-2"/>
   <button disabled={busy||!password} className="rounded bg-black p-2 text-white">Upload as draft</button>
  </form>
  <div className="grid gap-4 lg:grid-cols-[300px_1fr]"><aside className="space-y-2 rounded-xl border bg-white p-3">{sources.map(s=><button key={s.id} disabled={busy} onClick={()=>detail(s.id)} className="block w-full rounded border p-2 text-left text-sm disabled:opacity-50"><b>{s.book_name}</b> · {s.edition}<br/>{s.board} {s.class_number} {s.subject} · {s.status}</button>)}</aside>
  {selected&&<main className="space-y-4 rounded-xl border bg-white p-4"><div className="flex flex-wrap gap-2">{selected.status==="uploading"&&<button disabled={busy} onClick={()=>action("finalize_upload")} className="rounded bg-amber-700 px-3 py-2 text-white">Verify and finalize upload</button>}<button disabled={busy} onClick={()=>action("process")} className="rounded bg-blue-700 px-3 py-2 text-white">Process / Retry</button><button disabled={busy||selected.status!=="review"} onClick={generateSuggestions} className="rounded bg-indigo-700 px-3 py-2 text-white">Generate mapping suggestions</button><button onClick={openPdf} className="rounded border px-3 py-2">Review original PDF</button><button disabled={busy} onClick={()=>action("publish")} className="rounded bg-green-700 px-3 py-2 text-white">Publish</button><button disabled={busy} onClick={()=>action("unpublish")} className="rounded border px-3 py-2">Unpublish</button></div>
   <p className="text-sm">Status: <b>{selected.status}</b> · {selected.page_count||0} pages {selected.processing_error&&`· ${selected.processing_error}`}</p>
   <div className="rounded border border-amber-300 bg-amber-50 p-3 text-sm">Only pages inside mapped ranges need approval; unrelated pages may remain unreviewed. Every mapped page must be explicitly approved. Replacing any topic served by an existing publication withdraws that whole source, so this draft must also map every other topic served by that source. Partial replacements are rejected to protect those topics.</div>
   {suggestions.length>0&&<section className="space-y-2 rounded border border-indigo-200 bg-indigo-50 p-3"><div><h2 className="font-semibold">Proposed mappings</h2><p className="text-sm">PDF page numbers are used. Edit ranges, deselect uncertain proposals, then explicitly accept them into the draft.</p></div>{suggestions.map((item,index)=><div key={item.topicId} className="rounded border bg-white p-3 text-sm"><label className="flex gap-2"><input type="checkbox" disabled={busy} checked={item.selected} onChange={e=>setSuggestions(v=>v.map((x,i)=>i===index?{...x,selected:e.target.checked}:x))}/><span><b>{item.chapterName} → {item.topicName}</b><br/>Matched “{item.matchingHeading}” on PDF page {item.evidence[0]?.pageNumber}. {item.reason}</span></label><div className="mt-2 flex items-center gap-2"><span>PDF pages</span><input type="number" disabled={busy} min="1" max={selected.page_count} value={item.pageFrom} onChange={e=>setSuggestions(v=>v.map((x,i)=>i===index?{...x,pageFrom:Number(e.target.value)}:x))} className="w-20 border p-1"/><span>to</span><input type="number" disabled={busy} min="1" max={selected.page_count} value={item.pageTo} onChange={e=>setSuggestions(v=>v.map((x,i)=>i===index?{...x,pageTo:Number(e.target.value)}:x))} className="w-20 border p-1"/></div></div>)}<button type="button" disabled={busy} onClick={acceptSuggestions} className="rounded bg-indigo-800 px-3 py-2 text-white disabled:opacity-50">Accept selected into draft</button></section>}
   {unresolved.length>0&&<section className="rounded border border-amber-300 bg-amber-50 p-3 text-sm"><h2 className="font-semibold">Unresolved topics ({unresolved.length})</h2><div className="mt-2 space-y-2">{unresolved.map(item=><div key={item.topicId}><b>{item.chapterName} → {item.topicName}</b>: {item.reason}</div>)}</div></section>}
   <fieldset disabled={busy||selected.status!=="review"} className="grid gap-2 md:grid-cols-3"><select value={map.subjectId} onChange={e=>setMap({...map,subjectId:e.target.value,chapterId:"",topicId:""})} className="border p-2"><option value="">Subject</option>{catalog.map(s=><option key={s.id} value={s.id}>{s.board} {s.class_number} · {s.subject_name}</option>)}</select><select value={map.chapterId} onChange={e=>setMap({...map,chapterId:e.target.value,topicId:""})} className="border p-2"><option value="">Chapter</option>{subject?.chapters.map(c=><option key={c.id} value={c.id}>{c.chapter_name}</option>)}</select><select value={map.topicId} onChange={e=>setMap({...map,topicId:e.target.value})} className="border p-2"><option value="">Existing topic</option>{chapter?.topics.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.topic_name}</option>)}</select><input type="number" min="1" value={map.pageFrom} onChange={e=>setMap({...map,pageFrom:e.target.value})} className="border p-2"/><input type="number" min="1" value={map.pageTo} onChange={e=>setMap({...map,pageTo:e.target.value})} className="border p-2"/><button type="button" onClick={()=>{if(!map.subjectId||!map.chapterId||!map.topicId)return;setDraftMappings(v=>[...v.filter(x=>x.topicId!==map.topicId),map]);setMap({...map,topicId:""})}} className="rounded bg-slate-700 p-2 text-white">Add topic mapping</button><button type="button" onClick={()=>action("save_mappings",{mappings:draftMappings,...(acceptedSuggestionSource?{suggestionSource:acceptedSuggestionSource}:{})})} className="rounded bg-slate-900 p-2 text-white">Save all draft mappings ({draftMappings.length})</button></fieldset>
   <div className="space-y-1 text-sm">{draftMappings.map((m,i)=>{const s=catalog.find(x=>String(x.id)===m.subjectId),c=s?.chapters.find(x=>String(x.id)===m.chapterId),t=c?.topics.find(x=>String(x.id)===m.topicId);return <div key={m.topicId} className="flex justify-between rounded border p-2"><span>{t?.topic_name||`Topic ${m.topicId}`} · pages {m.pageFrom}–{m.pageTo}</span>{selected.status==="review"&&<button disabled={busy} onClick={()=>setDraftMappings(v=>v.filter((_,j)=>j!==i))} className="text-red-700 disabled:opacity-50">Remove</button>}</div>})}</div>
   <div className="space-y-3">{pages.map((p,i)=>{const mapped=draftMappings.some(m=>Number(m.pageFrom)<=p.page_number&&Number(m.pageTo)>=p.page_number);return <div key={p.page_number} className={`rounded border p-3 ${mapped&&p.review_status!=="approved"?"border-amber-500 bg-amber-50":""}`}><div className="mb-2 text-sm font-semibold">Page {p.page_number} · {p.review_status}{mapped?" · mapped, approval required":" · unmapped"}</div><textarea disabled={busy||selected.status!=="review"} value={p.reviewed_text??p.extracted_text} onChange={e=>setPages(v=>v.map((x,j)=>j===i?{...x,reviewed_text:e.target.value}:x))} className="h-40 w-full rounded border p-2 text-sm"/><div className="mt-2 flex gap-2"><button disabled={busy||selected.status!=="review"} onClick={()=>action("review",{pageNumber:p.page_number,reviewedText:p.reviewed_text??p.extracted_text,reviewStatus:"approved"})} className="rounded border px-2 py-1">Approve / save correction</button><button disabled={busy||selected.status!=="review"} onClick={()=>action("review",{pageNumber:p.page_number,reviewedText:p.reviewed_text??"",reviewStatus:"needs_ocr"})} className="rounded border px-2 py-1">Flag OCR/manual correction</button></div></div>})}</div>
  </main>}</div>
 </section>
}
