"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { supabaseBrowser } from "@/app/lib/supabaseBrowser";

type Source={id:string;book_name:string;edition:string;board:string;class_number:number;subject:string;status:string;page_count?:number;processing_error?:string};
type Page={page_number:number;extracted_text:string;reviewed_text?:string;review_status:string};
type Subject={id:number;board:string;class_number:number;subject_name:string;chapters:{id:number;chapter_name:string;topics:{id:number;topic_name:string;is_active:boolean}[]}[]};
type Mapping={subjectId:string;chapterId:string;topicId:string;pageFrom:string;pageTo:string};

export default function TextbooksPage(){
 const [password,setPassword]=useState(""); const [sources,setSources]=useState<Source[]>([]); const [selected,setSelected]=useState<Source|null>(null);
 const [pages,setPages]=useState<Page[]>([]); const [catalog,setCatalog]=useState<Subject[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 const [map,setMap]=useState({subjectId:"",chapterId:"",topicId:"",pageFrom:"1",pageTo:"1"});
 const [draftMappings,setDraftMappings]=useState<Mapping[]>([]);
 const headers=useMemo(()=>({"x-admin-password":password}),[password]);
 const load=useCallback(async()=>{if(!password)return;const [a,b]=await Promise.all([fetch("/api/admin/textbooks",{headers}),fetch("/api/admin/textbooks?catalog=1",{headers})]);const x=await a.json(),y=await b.json();if(x.ok)setSources(x.sources);if(y.ok)setCatalog(y.subjects||[]);},[headers,password]);
 useEffect(()=>{void load()},[load]);
 async function detail(id:string){const r=await fetch(`/api/admin/textbooks?id=${id}`,{headers}),d=await r.json();if(d.ok){setSelected(d.source);setPages(d.pages||[]);setDraftMappings((d.mappings||[]).map((m:any)=>({subjectId:String(m.subject_id),chapterId:String(m.chapter_id),topicId:String(m.topic_id),pageFrom:String(m.page_from),pageTo:String(m.page_to)})));setMap(m=>({...m,pageTo:String(d.source.page_count||1)}));}else setMessage(d.error);}
 async function upload(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setMessage("");
  try{
   const data=new FormData(e.currentTarget),file=data.get("pdf");if(!(file instanceof File))throw new Error("Choose a PDF.");
   const payload={board:data.get("board"),classNumber:data.get("classNumber"),subject:data.get("subject"),bookName:data.get("bookName"),edition:data.get("edition"),fileName:file.name,fileSize:file.size,fileType:file.type};
   const r=await fetch("/api/admin/textbooks",{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Could not prepare upload.");
   const uploaded=await supabaseBrowser.storage.from("textbook-pdfs").uploadToSignedUrl(d.upload.path,d.upload.token,file,{contentType:"application/pdf",upsert:false});
   if(uploaded.error)throw uploaded.error;
   const finalized=await fetch("/api/admin/textbooks",{method:"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({sourceId:d.source.id,action:"finalize_upload"})}),done=await finalized.json();
   if(!finalized.ok||!done.ok)throw new Error(done.error||"Upload could not be finalized.");
   setMessage("Draft uploaded directly to private storage. Run processing next.");await load();await detail(d.source.id);
  }catch(error:any){setMessage(error?.message||"Upload failed.")}finally{setBusy(false)}
 }
 async function action(action:string,extra:any={}){if(!selected)return;setBusy(true);const url=action==="process"?"/api/admin/textbooks/process":"/api/admin/textbooks";const body=action==="process"?{sourceId:selected.id}:{sourceId:selected.id,action,...extra};const r=await fetch(url,{method:action==="process"?"POST":"PATCH",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();setMessage(d.ok?`${action.replace("_"," ")} complete.`:d.error);await load();await detail(selected.id);setBusy(false);}
 async function openPdf(){if(!selected)return;const r=await fetch(`/api/admin/textbooks/pdf?id=${selected.id}`,{headers}),d=await r.json();if(d.ok)window.open(d.url,"_blank","noopener,noreferrer");else setMessage(d.error);}
 const subject=catalog.find(s=>String(s.id)===map.subjectId),chapter=subject?.chapters.find(c=>String(c.id)===map.chapterId);
 return <section className="space-y-5"><div><h1 className="text-2xl font-semibold">Textbook Teaching</h1><p className="text-sm text-slate-500">Private PDF ingestion, page review, curriculum mapping and publication.</p></div>
  {message&&<div className="rounded border bg-white p-3 text-sm">{message}</div>}
  <input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" className="w-full rounded border p-2"/>
  <form onSubmit={upload} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3">
   <input name="board" defaultValue="CBSE" required className="rounded border p-2"/><input name="classNumber" type="number" min="1" max="12" defaultValue="7" required className="rounded border p-2"/><input name="subject" defaultValue="English" required className="rounded border p-2"/>
   <input name="bookName" defaultValue="Poorvi" required placeholder="Book" className="rounded border p-2"/><input name="edition" required placeholder="Edition / year" className="rounded border p-2"/><input name="pdf" type="file" accept="application/pdf,.pdf" required className="rounded border p-2"/>
   <button disabled={busy||!password} className="rounded bg-black p-2 text-white">Upload as draft</button>
  </form>
  <div className="grid gap-4 lg:grid-cols-[300px_1fr]"><aside className="space-y-2 rounded-xl border bg-white p-3">{sources.map(s=><button key={s.id} onClick={()=>detail(s.id)} className="block w-full rounded border p-2 text-left text-sm"><b>{s.book_name}</b> · {s.edition}<br/>{s.board} {s.class_number} {s.subject} · {s.status}</button>)}</aside>
  {selected&&<main className="space-y-4 rounded-xl border bg-white p-4"><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>action("process")} className="rounded bg-blue-700 px-3 py-2 text-white">Process / Retry</button><button onClick={openPdf} className="rounded border px-3 py-2">Review original PDF</button><button disabled={busy} onClick={()=>action("publish")} className="rounded bg-green-700 px-3 py-2 text-white">Publish</button><button disabled={busy} onClick={()=>action("unpublish")} className="rounded border px-3 py-2">Unpublish</button></div>
   <p className="text-sm">Status: <b>{selected.status}</b> · {selected.page_count||0} pages {selected.processing_error&&`· ${selected.processing_error}`}</p>
   <div className="rounded border border-amber-300 bg-amber-50 p-3 text-sm">Only pages inside mapped ranges need approval; unrelated pages may remain unreviewed. Every mapped page must be explicitly approved. Replacing any topic served by an existing publication withdraws that whole source, so this draft must also map every other topic served by that source. Partial replacements are rejected to protect those topics.</div>
   <fieldset disabled={selected.status!=="review"} className="grid gap-2 md:grid-cols-3"><select value={map.subjectId} onChange={e=>setMap({...map,subjectId:e.target.value,chapterId:"",topicId:""})} className="border p-2"><option value="">Subject</option>{catalog.map(s=><option key={s.id} value={s.id}>{s.board} {s.class_number} · {s.subject_name}</option>)}</select><select value={map.chapterId} onChange={e=>setMap({...map,chapterId:e.target.value,topicId:""})} className="border p-2"><option value="">Chapter</option>{subject?.chapters.map(c=><option key={c.id} value={c.id}>{c.chapter_name}</option>)}</select><select value={map.topicId} onChange={e=>setMap({...map,topicId:e.target.value})} className="border p-2"><option value="">Existing topic</option>{chapter?.topics.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.topic_name}</option>)}</select><input type="number" min="1" value={map.pageFrom} onChange={e=>setMap({...map,pageFrom:e.target.value})} className="border p-2"/><input type="number" min="1" value={map.pageTo} onChange={e=>setMap({...map,pageTo:e.target.value})} className="border p-2"/><button type="button" onClick={()=>{if(!map.subjectId||!map.chapterId||!map.topicId)return;setDraftMappings(v=>[...v.filter(x=>x.topicId!==map.topicId),map]);setMap({...map,topicId:""})}} className="rounded bg-slate-700 p-2 text-white">Add topic mapping</button><button type="button" onClick={()=>action("save_mappings",{mappings:draftMappings})} className="rounded bg-slate-900 p-2 text-white">Save all draft mappings ({draftMappings.length})</button></fieldset>
   <div className="space-y-1 text-sm">{draftMappings.map((m,i)=>{const s=catalog.find(x=>String(x.id)===m.subjectId),c=s?.chapters.find(x=>String(x.id)===m.chapterId),t=c?.topics.find(x=>String(x.id)===m.topicId);return <div key={m.topicId} className="flex justify-between rounded border p-2"><span>{t?.topic_name||`Topic ${m.topicId}`} · pages {m.pageFrom}–{m.pageTo}</span>{selected.status==="review"&&<button onClick={()=>setDraftMappings(v=>v.filter((_,j)=>j!==i))} className="text-red-700">Remove</button>}</div>})}</div>
   <div className="space-y-3">{pages.map((p,i)=>{const mapped=draftMappings.some(m=>Number(m.pageFrom)<=p.page_number&&Number(m.pageTo)>=p.page_number);return <div key={p.page_number} className={`rounded border p-3 ${mapped&&p.review_status!=="approved"?"border-amber-500 bg-amber-50":""}`}><div className="mb-2 text-sm font-semibold">Page {p.page_number} · {p.review_status}{mapped?" · mapped, approval required":" · unmapped"}</div><textarea disabled={selected.status!=="review"} value={p.reviewed_text??p.extracted_text} onChange={e=>setPages(v=>v.map((x,j)=>j===i?{...x,reviewed_text:e.target.value}:x))} className="h-40 w-full rounded border p-2 text-sm"/><div className="mt-2 flex gap-2"><button disabled={selected.status!=="review"} onClick={()=>action("review",{pageNumber:p.page_number,reviewedText:p.reviewed_text??p.extracted_text,reviewStatus:"approved"})} className="rounded border px-2 py-1">Approve / save correction</button><button disabled={selected.status!=="review"} onClick={()=>action("review",{pageNumber:p.page_number,reviewedText:p.reviewed_text??"",reviewStatus:"needs_ocr"})} className="rounded border px-2 py-1">Flag OCR/manual correction</button></div></div>})}</div>
  </main>}</div>
 </section>
}
